### ISSUE TITLE
Package type "drupal-console-library" is not supported

### ISSUE THREAD

**Issue by sharif-elshobkshy** [weknowinc/drupal-console-dotenv#9]
Hi,

I'm using drupal/console. I have it in my composer.json . 
When executing `composer install` or `composer update`, I get the following error message:

`  [InvalidArgumentException] 
   Package type "drupal-console-library" is not supported `

I see that Drupal Console requires "drupal-console-dotenv", and this package/library has a type "drupal-console-library".

I have been using Drupal Console for a long time in the project (in my composer.json) and never had any issues. So it's weird that now out of the blue I get that message. 

Was something updated?

Thanks in advance,
Sharif.

**Comment by fazni** [comment]
Hi,
I'm facing the same issue as you.

You have any leads ?

Ping @jmolivas 

Thanks
Said

**Comment by jmolivas** [comment]
Probably @enzolutions should have any idea of this? maybe related to the composer-installer PR you sent?

**Comment by sharif-elshobkshy** [comment]
@fazni 

I was able to fix this by adding the "drupal-console-library" in the installer paths in the composer.json


"extra": {
    "installer-paths": {
        "web/libraries/{$name}": ["type:drupal-library", "**type:drupal-console-library**"]
    },
}

I was also having issues with the new version of doctrine/lexer, so I had to freeze (for now) the version.

"require": {
    "doctrine/lexer": "1.0.2"
},

Hope this helps you.
Regards.

**Comment by fazni** [comment]
@sharif-elshobkshy  thanks for your feedback.

**Comment by f1rf1n** [comment]
@sharif-elshobkshy Yes, thank you for the feedback! 
This brought my composer back to life (I could not even do a composer info without the installer-path being set.)

**Comment by enzolutions** [comment]
The latest version [0.3.1](https://github.com/weknowinc/drupal-console-dotenv/releases/tag/0.3.1)+ Removed composer packagist type
